### ISSUE TITLE
graphical support

### ISSUE THREAD

**Issue by Luminoso-256** [meme/limbo#4]
Hey there!

Just as a pure curiosity - is it even hypothetically possible for the project to support graphics? Perhaps via populating more of the chroot, and running something like XQuartz?

**Comment by meme** [comment]
Yes, it is certainly possible to achieve graphics.

First, proper Mach messaging is needed. Right now it is emulated in-process and only a few kernel messages are supported. This means it is not possible to run launchd as an init in the chroot.

Next is the graphics stack itself. There are multiple different ways to do this, depending on the desired result. You could re-implement CoreGraphics on Linux with something like Cairo, and this would allow primitive drawing to work. For getting a handle to a display device, it would probably make sense to create a simple framebuffer and feed the results through, that will require IOKit.

Thus, an IOKit shim layer is needed such that we can implement IOKit drivers inside of Limbo. Then we can implement fake displays, or even fake graphics devices (although for Metal this will require that Mesa supports Metal, which is something that a few other members of the community are interested in, but will be a lot for work with pushback, as Metal is not formally specified)
